### ISSUE TITLE
メッセージ入力欄で2回エンター押すと2重投稿される

### ISSUE THREAD

**Issue by uchan-nos** [HSKKOU/RelayPrograming#36]
メッセージ入力欄にチャットメッセージを書き込み、1回エンターを押してからページがリロードされるまでに再度エンターを押すと2重投稿される。1回目のエンターの後、メッセージが残っているため、遅い回線だとつい2回エンターしてしまう。
N回押したときにN重投稿されるかまでは未確認。

**Comment by HSKKOU** [comment]
フラグ管理が雑で申し訳ありませんでした。
修正完了です。
