### ISSUE TITLE
ときどき2重ログインされる

### ISSUE THREAD

**Issue by uchan-nos** [HSKKOU/RelayPrograming#37]
再現する手順は不明。ときどき2重にログインされることがある。次のような症状が出る。
- メンバーリスト欄に同じ名前が2つ表示される。
- 一度のエンター押下で重複して投稿される。（コードも、チャットメッセージも）

**Comment by HSKKOU** [comment]
#36 と同じ種類のバグだと思います。
同じような方法で修正をしました
