### ISSUE TITLE
Admin 画面で行数非表示機能がほしい

### ISSUE THREAD

**Issue by uchan-nos** [HSKKOU/RelayPrograming#38]
バグではなく機能要望。
司会者はAdmin画面を使うことが主だと思うが、Admin画面では行数非表示機能がないのでIdeoneへのPOSTが不便。
Admin画面にこそ行数非表示機能が欲しい。

**Comment by HSKKOU** [comment]
adminにも行数表示非表示機能をつけました
夏ゼミの時は自分がUserかつAdminをやっていたので気づきませんでした
